apply plugin: 'java'

dependencies {
    testImplementation "junit:junit:4.12"
    testImplementation 'com.squareup.okio:okio:1.11.0'
    testImplementation 'org.assertj:assertj-core:3.6.2'

    // AGP / Guava 只作为编译期 classpath 依赖，不打进最终产物
    compileOnly "com.android.tools.build:gradle:$android_tools_version"
    implementation project(':lancet-base')
    implementation gradleApi()
    compileOnly "com.google.guava:guava:$guava_version"
    implementation "org.ow2.asm:asm-all:$asm_version"
}

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

